version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000" # For FastAPI
      - "3000:3000" # For Dagster UI
    volumes:
      - .:/app
    env_file:
      - .env # Load environment variables from the .env file
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env # Load database credentials from the .env file

volumes:
  postgres_data:
