analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: your_username
      password: your_super_secret_password
      port: 5432
      dbname: medical_data
      schema: public
      threads: 4
